###
GET {{EXPO_PUBLIC_API_URL}}/api/auth/me

###
POST {{EXPO_PUBLIC_API_URL}}/api/auth/password/login

{
  "email":"one@gmail.com",
  "password":"123Clashofclan@"
}

###
POST {{EXPO_PUBLIC_API_URL}}/api/auth/password/register

{
  "email":"one@gmail.com",
  "password":"123Clashofclan@",
  "confirmPassword":"123Clashofclan@"
}
