// packages/crypto/src/argon2.ts
import { argon2id } from "@noble/hashes/argon2";

export interface DerivedKey {
  mek: Uint8Array;
  salt: Uint8Array;
}

/**
 * Argon2id Configuration
 * These parameters balance security and mobile performance.
 */
const ARGON2_CONFIG = {
  t: 3, // Iterations (Time cost)
  m: 19456, // ~19MB Memory cost (OWASP minimum for Argon2id; mobile-safe)
  p: 1, // Parallelism (Threads)
  dkLen: 32, // 256-bit output
};

/**
 * Generates a new MEK using Argon2id with an externally-provided salt.
 * Salt must be generated by the caller using the platform's crypto API.
 */
export function generateInitialMEK(
  password: string,
  salt: Uint8Array,
): DerivedKey {
  // Argon2id is more resistant to GPU/ASIC attacks than PBKDF2
  const mek = argon2id(password, salt, ARGON2_CONFIG);

  return { mek, salt };
}

/**
 * Re-generates the MEK using a password and a retrieved salt
 */
export function recoverMEK(password: string, salt: Uint8Array): Uint8Array {
  return argon2id(password, salt, ARGON2_CONFIG);
}
